def main():
    print("hello all welcome to magic python")
    print("the rules are simple. you have to pick random 4 digit number whenever i say you.")
    print("so you go first. give me your number digit by digit: ")
    n1=int(input())
    n2=int(input())
    n3=int(input())
    n4=int(input())
    n=("%d%d%d%d" %(n1,n2,n3,n4))
    print("now i'm gonna give you a number. keep that in mind until its over")
    m1=2
    m2=n1
    m3=n2
    m4=n3
    m5=(n4-2)
    print("my number is: ")
    number=("%d%d%d%d%d" %(m1,m2,m3,m4,m5))
    print(number)
    print("now give me your 2nd 4digit number. enter this as you done early")
    a1=int(input())
    a2=int(input())
    a3=int(input())
    a4=int(input())
    a=("%d%d%d%d" %(a1,a2,a3,a4))
    print("mm good! its my turn now my number is: ")
    x1=(9-a1)
    x2=(9-a2)
    x3=(9-a3)
    x4=(9-a4)
    x=("%d%d%d%d" %(x1,x2,x3,x4))
    print(x)
    print("again your turn: ")
    b1=int(input())
    b2=int(input())
    b3=int(input())
    b4=int(input())
    b=("%d%d%d%d" %(b1,b2,b3,b4))
    print("my number is:")
    y1=(9-b1)
    y2=(9-b2)
    y3=(9-b3)
    y4=(9-b4)
    y=("%d%d%d%d" %(y1,y2,y3,y4))
    print(y)
    print("so thats all. just add all 5 numbers. for quick reference i will list down")
    print(n)
    print(a)
    print(x)
    print(b)
    print(y)
    print("do you remember the digit i told you begining?")
    print(number)

    print("do you wanna play try again? y/n")
    restart=input()
    if restart == "y":
        main()
    else:
        print("hope you enjoyed this. see ya next time.")
        exit()
main()